---
- name: Create MetalLB configuration file
  copy:
    src: files/{{ item }}
    dest: ${HOME}/{{ item }}
  become: true
  become_user: "{{ install_user}}"
  loop:
    - metallb-config.yaml
    - myenvironment-metallb.yaml
- name: Create MetalLB module
  shell: |
    olcnectl module create --config-file myenvironment-metallb.yaml
  become_user: "{{ install_user}}"
  register: ocne_module_create
- name: DEBUG output
  debug:
    var: ocne_module_create
  when: debug_output == true
- name: Validate MetalLB module
  shell: |
    olcnectl module validate --config-file myenvironment-metallb.yaml
  become_user: "{{ install_user}}"
  register: ocne_module_validate
- name: DEBUG output
  debug:
    var: ocne_module_validate
  when: debug_output == true
- name: Install MetalLB module
  shell: |
    olcnectl module install --config-file myenvironment-metallb.yaml
  become_user: "{{ install_user}}"
  register: ocne_module_install
- name: DEBUG output
  debug:
    var: ocne_module_install
  when: debug_output == true
- name: Gather installed modules
  shell: |
    olcnectl module instances --config-file myenvironment-metallb.yaml
  become_user: "{{ install_user}}"
  register: ocne_module_instances
- name: Show installed modules
  debug:
    var: ocne_module_instances